// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Axios: typeof import('./src/components/axios.vue')['default']
    copy: typeof import('./src/components/defineEmits copy.vue')['default']
    DefineEmits: typeof import('./src/components/defineEmits.vue')['default']
    DefineExpose: typeof import('./src/components/defineExpose.vue')['default']
    DefineProps: typeof import('./src/components/defineProps.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Props: typeof import('./src/components/Props.vue')['default']
    Request: typeof import('./src/components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseRequest: typeof import('./src/components/useRequest.vue')['default']
    UseUserStore: typeof import('./src/components/useUserStore.vue')['default']
    VueUse: typeof import('./src/components/vueUse.vue')['default']
    WordLight: typeof import('./src/components/wordLight.vue')['default']
  }
}
